name: GodllyCore
version: '2.2.0'
main: dev.casperschotman.godllyCore.GodllyCore
api-version: '1.20'
author: ItzRepsac_ / Casper
commands:
  core:
    description: Main command for GodllyCore plugin.
    permission: godllycore.admin
    usage: /<command> <subcommand>
    aliases: [core]
  fly:
    description: Allows players to toggle fly mode and set fly speed
    usage: /<command> [speed <value> | speed reset]
    permission: godllycore.fly
    permission-message: You do not have permission to use the fly command.
  gmc:
    description: Set game mode to Creative
    usage: /gmc [player]
    permission: godllycore.gamemode.creative
  gms:
    description: Set game mode to Survival
    usage: /gms [player]
    permission: godllycore.gamemode.survival
  gmsp:
    description: Set game mode to Spectator
    usage: /gmsp [player]
    permission: godllycore.gamemode.spectator
  gma:
    description: Set game mode to Adventure
    usage: /gma [player]
    permission: godllycore.gamemode.adventure
  tp:
    description: Teleport to another player
    usage: /tp <player>
    permission: godllycore.teleport.tp
    permission-message: You do not have permission to use this command!
  tphere:
    description: Teleport a player to you
    usage: /tphere <player>
    permission: godllycore.teleport.tphere
    permission-message: You do not have permission to use this command!
  tpall:
    description: Teleport all players to you
    usage: /tpall
    permission: godllycore.teleport.tpall
    permission-message: You do not have permission to use this command!
  tpa:
    description: Send a teleport request to another player
    usage: /tpa <player>
    permission: godllycore.teleport.tpa
    permission-message: You do not have permission to use this command!
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
    permission: godllycore.teleport.tpaccept
    permission-message: You do not have permission to use this command!
  tpadeny:
    description: Deny a teleport request
    usage: /tpadeny
    permission: godllycore.teleport.tpadeny
    permission-message: You do not have permission to use this command!
  drop:
    description: Command to toggle cooldown bypass and drop items
    usage: /<command> [toggle]
  vanish:
    description: Toggles vanish mode for the player.
    usage: /vanish
    permission: godllycore.vanish
    permission-message: You do not have permission to use this command.
  toggleinvfull:
    description: Toggle inventory full title notification
    usage: /invfulltoggle
    permission: godllycore.toggleinvfull
permissions:
  godllycore.fly:
    description: Allows players to toggle fly mode
    default: op
  godllycore.fly.speed:
    description: Allows players to set their fly speed
    default: op
  godllycore.vanish:
    description: Allows the player to vanish.
    default: op
  godllycore.vanish.see:
    description: Allows the player to see vanished players.
    default: false
  godllycore.viewplugins:
    description: Allows players to view plugin-related commands like /pl, /plugins, /reload, etc.
    default: op
  godllycore.core:
    description: Allows the player to execute the /godllycore command and its subcommands
    default: op
  godllycore.reload:
    description: Allows the player to reload the plugin configuration
    default: op
  godllycore.restart:
    description: Allows the player to initiate a server restart with a countdown
    default: op
  godllycore.drop.bypass:
    description: Allows staff to bypass the drop cooldown
    default: op
  godllycore.gamemode.*:
    description: Allows access to all gamemode commands
    default: op
  godllycore.gamemode.creative:
    description: Allows setting gamemode to Creative
    default: op
  godllycore.gamemode.survival:
    description: Allows setting gamemode to Survival
    default: op
  godllycore.gamemode.spectator:
    description: Allows setting gamemode to Spectator
    default: op
  godllycore.gamemode.adventure:
    description: Allows setting gamemode to Adventure
    default: op
  godllycore.gamemode.others:
    description: Allows setting another player's gamemode
    default: op
  godllycore.toggleinvfull:
    description: Allows players to toggle inventory full notification
    default: true